config/routes.rb
Propertymanagement::Application.routes.draw do
  resources :roles

  resources :user_sessions

  resources :repair_requests

  resources :users

  resources :leases

  resources :units

  resources :properties
  
  root :to => 'users#index'
  
  match 'login', :to => 'user_sessions#new'
  
  match 'logout', :to => 'user_sessions#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Property Management</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="wrapper">
		<div class="header">
			<a href="<%= root_url %>">Property Management</a>
		</div>
		<div class="navigation">
			<ul>
				<li><a href="<%= root_url %>">Home</a></li>
				<li><% if current_user %>
						<%= link_to "Repair Requests", repair_requests_path %>
					<% end %>
				</li>
				<li><% if current_user %>
						<%= link_to "Leases", leases_path %>
					<% end %>
				</li>
			</ul>
			<div style="float: right; height: 27px; line-height: 27px; padding-right: 5px;">
				<% if current_user %>
					<%= link_to "Edit Profile", edit_user_path(current_user.id) %>
					<%= link_to "Logout", logout_path %>
				<% else %>				
			        <%= link_to "Register", new_user_path %>
			        <%= link_to "Login", login_path %>
				<% end %>
			</div>
		</div>
		<div class="body">
			<% if flash[:notice] %>
		      <p class="notice"><%= flash[:notice] %></p>
		    <% end %>
			<%= yield %>
		</div>
		<div class="footer">
			Copyright 201*, Property Management
		</div>
	</div>
</body>
</html>